export const mockLoanProduct = {
   product: {
      name: 'Test Product',
      currency: 'USD',
   },
   customerName: 'John Doe',
   acctNo: '123456',
   loanAssets: [{ name: 'Asset 1' }],
};

export const mockCustomerData = {
   customerId: '12345',
   customerType: 'Individual',
   status: 'Active',
   monitoring: true,
   isTerminated: false,
   approvalStatus: 'Approved',
   initiator: 'John Doe',
   initiatorId: '6789',
   approver: 'Jane Smith',
   approverId: '9876',
   createdAt: '2022-01-15',
   updatedAt: '2022-10-20',
   customer_profiles: [
      {
         firstName: 'John',
         surname: 'Doe',
         otherNames: 'Smith',
         bvn: '1234567890',
         mobileNumber: '9876543210',
      },
   ],
   customer_products: [
      {
         productId: '78901',
         productName: 'Savings Account',
      },
      {
         productId: '23456',
         productName: 'Credit Card',
      },
   ],
   risk_assessments: [],
   signatories: [],
   executives: [],
   other_accounts: [],
   customer_account_balances: [],
   requests: [],
   hasRequestInReview: false,
   riskStatus: 'Low',
   riskScore: 75,
};

export const mockProductData = {
   id: '1',
   name: 'Sample Loan Product',
   description: 'This is a sample loan product',
   code: 'LP001',
   type: 'Personal Loan',
   typeId: '1',
   category: 'Consumer',
   categoryId: '1',
   subCategory: 'Unsecured',
   subCategoryId: '1',
   currency: 'USD',
   currencyId: '1',
   maxLoanTenure: 36,
   maxLoanTenurePeriod: 'Months',
   minLoanTenure: 6,
   minLoanTenurePeriod: 'Months',
   minLoanPrincipal: 1000,
   maxLoanPrincipal: 5000,
   minInterestRate: 5,
   maxInterestRate: 10,
   allowMultipleReq: true,
   isDraft: false,
   status: 'Active',
   requestStatus: 'Approved',
   createdById: 'user123',
   createdBy: 'John Doe',
   dateCreated: '2023-01-15T08:00:00Z',
   lastModifiedById: 'user456',
   lastModifiedBy: 'Jane Smith',
   lastModifiedDate: '2023-02-20T14:30:00Z',
   approvedBy: 'manager789',
   approvedById: 'manager789',
   approvedDate: '2023-02-22T10:15:00Z',
   tenantId: 'tenant123',
   deletedDate: null,
   deletedById: null,
   deleteBy: null,
   currentStep: 2,
   productEligibilityCriteriaRequirement: { requireEquityContrib: true },
};

export const mockedBookLoanData = {
   customerInformation: {
      acctNo: '1234567890',
   },
   facilityDetails: {
      product_name: 'Loan Product 1',
      product_category: 'Category 1',
      productPurpose: 'Purchase',
      principal: '10000',
      interestRate: '5',
      tenorValue: '12',
      tenorPeriod: 'Months',
      repayment_pattern: 'Pattern 1',
      repayment_frequency: 'Monthly',
      start_date: '2023-10-01',
      start_date_num: '1',
      start_date_period: 'Months',
      collaterals: [
         {
            id: 'collateral1',
            collateral_market_value: '5000',
            collateral_file: 'collateral-file-1.pdf',
         },
         {
            id: 'collateral2',
            collateral_market_value: '7000',
            collateral_file: 'collateral-file-2.pdf',
         },
      ],
      isMoratoriumReq: true,
      moratoriumPeriod: '3',
      moratoriumValue: 'Months',
      recognize_moratorium_period: false,
      isGraceReq: true,
      gracePeriod: '2',
      graceValue: 'Months',
   },
   transactionSettings: {
      disburseMethd: 'Method 1',
      disburseAcct: 'Account 1',
      disburseDate: '2023-10-15',
      otherAcctNo: 'Other Account 1',
      isDisburseNotReq: false,
      notificationChannel: ['Email', 'SMS'],
      repaymentChannel: 'Direct Debit',
      repaymentAcct: 'Repayment Account 1',
   },
};
