export const Permissions = {
   BOOK_LOAN: 'BOOK_LOAN',
   LIQUIDATE_LOAN: 'LIQUIDATE_LOAN',
   VIEW_ALL_LOAN_RECORDS: 'VIEW_ALL_LOAN_RECORDS',
   VIEW_ALL_LOAN_REQUESTS: 'VIEW_ALL_LOAN_REQUESTS',
   WRITE_OFF_LOAN: 'WRITE_OFF_LOAN',
   AUTHORIZE_BOOKING_RESTRUCTURING_REQUESTS: 'AUTHORIZE_BOOKING/RESTRUCTURING_REQUESTS',
   AUTHORIZE_LIQUIDATION_WRITE_OFF_REQUESTS: 'AUTHORIZE_LIQUIDATION/WRITE-OFF_REQUESTS',
} as const;
