export const Permissions = {
   BOOK_LOAN: 'BOOK_LOAN',
   LIQUIDATE_LOAN: 'LIQUIDATE_LOAN',
   VIEW_ALL_LOAN_RECORDS: 'VIEW_ALL_LOAN_RECORDS',
   VIEW_ALL_LOAN_REQUESTS: 'VIEW_ALL_LOAN_REQUESTS',
   'WRITE-OFF_LOAN': 'WRITE-OFF_LOAN',
} as const;
