export interface LoanProductData {
   id: string;
   name: string;
   description: string;
   code: string;
   type: string;
   typeId: string | null;
   category: string;
   categoryId: string | null;
   subCategory: string | null;
   subCategoryId: string | null;
   currency: string;
   currencyId: string;
   maxLoanTenure: number;
   maxLoanTenurePeriod: string;
   minLoanTenure: number;
   minLoanTenurePeriod: string;
   minLoanPrincipal: number;
   maxLoanPrincipal: number;
   minInterestRate: number;
   maxInterestRate: number;
   allowMultipleReq: boolean;
   isDraft: boolean;
   status: string;
   requestStatus: string;
   createdById: string;
   createdBy: string;
   dateCreated: string;
   lastModifiedById: string | null;
   lastModifiedBy: string | null;
   lastModifiedDate: string | null;
   approvedBy: string | null;
   approvedById: string | null;
   approvedDate: string | null;
   tenantId: string | null;
   deletedDate: string | null;
   deletedById: string | null;
   deleteBy: string | null;
   currentStep: number;
}
