import { LoanProductData } from '@app/@types/loan-product';
import { mapBookLoanToSchema, mapSchemaToBookLoan, mapRepaymentScheduleToSchema } from '../book-loan-mapper';
import { CustomerData } from '@app/@types/customer';

describe('Loan Mapping Functions', () => {
   const sampleCustomerData: CustomerData = {
      customerId: 'CUST123',
      customerType: 'Individual',
      status: 'Active',
      monitoring: true,
      isTerminated: false,
      approvalStatus: 'Approved',
      tenantId: 'TENANT001',
      initiator: 'John Doe',
      initiatorId: 'USER001',
      approver: 'Manager',
      approverId: 'MANAGER001',
      team: 'Sales',
      teamId: 'TEAM001',
      createdAt: '2024-01-01',
      updatedAt: '2024-01-02',
      customer_profiles: [
         {
            customerProfileId: 'PROFILE001',
            customerId: 'CUST123',
            customerNumber: 'CUS001',
            customerEntityId: 'ENTITY001',
            bvn: '1234567890',
            email: 'john.doe@example.com',
            title: 'Mr.',
            relationshipOfficer: 'Jane Smith',
            emailAddress: 'john.doe@example.com',
            dateOfBirth: '1990-01-01',
            firstName: 'John',
            surname: 'Doe',
            gender: 'Male',
            idNumber: 'ID123456',
            idType: 'Passport',
            mobileNumber: '1234567890',
            nationality: 'Nigerian',
            otherNames: 'Smith',
            residentialAddress: '123 Main St',
            residentialAddressCity: 'Cityville',
            residentialAddressCountry: 'Nigeria',
            residentialAddressLGA: 'Local Gov',
            residentialAddressState: 'Stateville',
            stateOfOrigin: 'Stateville',
            nin: 'NIN123',
            cac: 'CAC001',
            tin: 'TIN001',
            mothersMaidenName: 'Doe',
            maritalStatus: 'Single',
            country: 'Nigeria',
            lga: 'Local Gov',
            cityTown: 'Cityville',
            dualCitizenship: 'Yes',
            ifYesSpecify: 'USA',
            chooseAnId: 'Passport',
            issueDate: '2010-01-01',
            expiryDate: '2030-01-01',
            detailedAddressOfResidentialAddress: '123 Main St, Cityville, Stateville',
            alternateMobileNumber: '0987654321',
            mailingAddressSameAsResidentialAddress: 'Yes',
            donok_title: 'Mrs.',
            donok_surname: 'Donok',
            donok_firstName: 'Jane',
            donok_otherNames: 'Doe',
            relationship: 'Mother',
            donok_gender: 'Female',
            donok_dateOfBirth: '1960-01-01',
            donok_detailedDescriptionOfResidentialAddress: '456 Second St, Cityville, Stateville',
            customersPhoto: 'base64encodedimage',
         },
      ],
      customer_products: [],
      risk_assessments: [],
      signatories: [],
      executives: [],
      other_accounts: [],
      customer_account_balances: [
         {
            customerAccountBalanceId: 'BALANCE001',
            customerId: 'CUST123',
            productId: 'PROD001',
            accountNumber: '123456789',
            openingBalance: '50000',
            operatingBalance: '45000',
            closingBalance: '55000',
            availableBalance: '48000',
            totalBalance: '55000',
            processed: true,
            status: 'Active',
            createdAt: '2024-01-01',
            updatedAt: '2024-01-02',
            ledgerId: 'LEDGER001',
         },
         // Add more balances if needed
      ],
      requests: [],
      requestInReview: null,
      hasRequestInReview: false,
      riskStatus: 'Low',
      riskScore: 75,
   };

   const sampleProductData: LoanProductData = {
      id: 'PROD001',
      name: '',
      description: '',
      code: '',
      type: '',
      category: '',
      currency: '',
      currencyId: '',
      maxLoanTenure: 0,
      maxLoanTenurePeriod: '',
      minLoanTenure: 0,
      minLoanTenurePeriod: '',
      minLoanPrincipal: 200,
      maxLoanPrincipal: 500,
      minInterestRate: 0,
      maxInterestRate: 0,
      allowMultipleReq: false,
      isDraft: false,
      requestStatus: '',
      createdById: '',
      createdBy: '',
      dateCreated: '',
      tenantId: '',
      currentStep: 0,
      productEligibilityCriteriaRequirement: {
         status: '',
         earnType: '',
         earnValue: 120,
         earnPeriodValue: 20,
         earnPeriod: '',
         requireEarning: true,
         requireEquityContrib: true,
         equityContribType: '',
         contribValueFrom: 23,
         contribValueTo: 30,
         requireSecurity: true,
         requireOtherEligibilityCriteria: false,
         hasEligibility: true,
         isDraft: false,
         productId: '',
         eligibilityCriteriaSecurityDocs: '',
         id: '',
         approvedBy: '',
         approvedById: '',
         approvedDate: '',
         lastModifiedById: '',
         lastModifiedBy: '',
         lastModifiedDate: '',
         createdById: '',
         createdBy: '',
         dateCreated: '',
         tenantId: '',
         deletedDate: '',
         deletedById: '',
         deleteBy: '',
      },
      pricingConfiguration: {
         id: '',
         intCalcMethod: '',
         intComputeDays: ' ',
         intRateConfigBand: '',
         productId: '',
         deleteBy: '',
         deletedById: '',
         deletedDate: '',
      },
      chargesTaxesPenalty: [],
   };

   const sampleBookLoanData: any = {
      id: 'LOAN001',
      facilityDetails: {
         principal: 300,
      },
      productId: 'PROD001',
      customerName: 'John Doe',
      customerId: 'CUST123',
      acctNo: '123456789',
      bvn: '9876543210',
      productPurpose: 'Home Loan',
      principal: 300,
      interestRate: 5.5,
      tenorValue: 12,
      tenorPeriod: 'months',
      isMoratoriumReq: true,
      moratoriumValue: 3,
      moratoriumPeriod: 'months',
      moratoriumDuration: 'Before Start',
      isGraceReq: true,
      graceValue: 1,
      totalRepayment: 60000,
      principalBalance: 45000,
      interestBalance: 7500,
      arrears: 0,
      penaltyDue: 0,
      gracePeriod: 'months',
      disburseMethd: 'Direct Deposit',
      disburseAcct: '987654321',
      disburseDate: '2024-03-01',
      otherAcctNo: '876543210',
      isDisburseNotReq: false,
      notificationChannel: 'Email',
      repaymentChannel: 'Auto Debit',
      repaymentSource: 'Salary',
      repaymentAcct: '765432109',
      status: 'Active',
      tenantId: 'TENANT001',
      createdBy: 'John Doe',
      createdById: 'USER001',
      dateCreated: '2024-01-01',
      lastModifiedById: null,
      lastModifiedBy: '',
      lastModifiedDate: null,
      approvedBy: 'Manager',
      approvedById: 'MANAGER001',
      approvedDate: '2024-01-02',
      deletedDate: null,
      deletedById: null,
      deleteBy: '',
      requestStatus: 'Approved',
      repaymentPattern: 'Equal Installments',
      repaymentFrequency: 'Monthly',
      repaymentFrequencyStartDate: '2024-02-01',
      repaymentFrequencyValue: '1',
      repaymentFrequencyPeriod: 'months',
      equityContribution: 10000,
      product: {
         id: 'PROD001',
         name: 'Home Loan',
         description: 'Mortgage for Home Purchase',
         code: 'HL001',
         type: 'Mortgage',
         typeId: 'TYPE001',
         category: 'Housing',
         categoryId: 'CAT001',
         subCategory: 'Single Family',
         subCategoryId: 'SUBCAT001',
         currency: 'USD',
         currencyId: 'USD001',
         maxLoanTenure: 360,
         maxLoanTenurePeriod: 'months',
         minLoanTenure: 12,
         minLoanTenurePeriod: 'months',
         minLoanPrincipal: 10000,
         maxLoanPrincipal: 1000000,
         minInterestRate: 4.5,
         maxInterestRate: 7.5,
         allowMultipleReq: true,
         isDraft: false,
         status: 'Active',
         requestStatus: 'Approved',
         createdById: 'USER001',
         createdBy: 'John Doe',
         dateCreated: '2024-01-01',
         lastModifiedById: undefined,
         lastModifiedBy: '',
         lastModifiedDate: undefined,
         approvedBy: 'Manager',
         approvedById: 'MANAGER001',
         approvedDate: '2024-01-02',
         tenantId: 'TENANT001',
         deletedDate: undefined,
         deletedById: undefined,
         deleteBy: '',
         currentStep: 3,
         productEligibilityCriteriaRequirement: {
            earnType: 'Salary',
            earnValue: 50000,
            earnPeriodValue: 12,
            earnPeriod: 'months',
            requireEarning: true,
            requireEquityContrib: true,
            equityContribType: 'Fixed',
            contribValueFrom: 10000,
            contribValueTo: 50000,
            requireSecurity: true,
            requireOtherEligibilityCriteria: true,
            hasEligibility: true,
            isDraft: false,
            productId: 'PROD001',
            eligibilityCriteriaSecurityDocs: null,
            id: 'ELIGIBILITY001',
            approvedBy: 'Manager',
            approvedById: 'MANAGER001',
            approvedDate: '2024-01-02',
            lastModifiedById: undefined,
            lastModifiedBy: '',
            lastModifiedDate: undefined,
            createdById: 'USER001',
            createdBy: 'John Doe',
            dateCreated: '2024-01-01',
            tenantId: 'TENANT001',
            deletedDate: '',
            deletedById: '',
            deleteBy: '',
         },
         pricingConfiguration: [],
         chargesTaxesPenalty: [],
         accountingEntry: null,
      },
      loanAssets: [],
      loanActivities: [
         {
            id: 'ACTIVITY001',
            commentText: 'Loan approved',
            action: 'Approval',
            loanId: 'LOAN001',
            createdById: 'MANAGER001',
            createdBy: 'Manager',
            dateCreated: '2024-01-02',
            lastModifiedById: null,
            lastModifiedBy: '',
            lastModifiedDate: null,
            approvedBy: '',
            approvedById: null,
            approvedDate: null,
            tenantId: 'TENANT001',
            deletedDate: null,
            deletedById: null,
            deleteBy: '',
         },
      ],
   };

   it('should map BookLoanData to schema correctly', () => {
      const mappedData = mapBookLoanToSchema(sampleBookLoanData, sampleCustomerData, sampleProductData);

      expect(mappedData.customerName).toEqual('John Smith Doe');
      expect(mappedData.productId).toEqual('PROD001');
   });

   it('should map schema to BookLoanData correctly', () => {
      const mappedLoanData: any = mapSchemaToBookLoan(sampleBookLoanData);

      expect(mappedLoanData.customerInformation.acctNo).toEqual('123456789');
      expect(mappedLoanData.facilityDetails.product_name).toEqual('Home Loan');
   });

   it('should map repayment schedule to schema correctly', () => {
      const mappedRepaymentSchedule = mapRepaymentScheduleToSchema(sampleBookLoanData, sampleProductData);

      expect(mappedRepaymentSchedule.principal).toEqual(300);
   });
});
